Add git diff details back

diff --git a/.github/workflows/otlp_nr_mapping.yml b/.github/workflows/otlp_nr_mapping.yml
--- a/.github/workflows/otlp_nr_mapping.yml
+++ b/.github/workflows/otlp_nr_mapping.yml
@@ -30,5 +30,5 @@ jobs:
         run: ./gradlew :otlp-nr-mapping:run
       - name: Detect changes
         run: |
-          [[ -z $(git status --porcelain) ]]
+          [[ -z $(git status --porcelain) ]] && echo "Success! No changes detected." || (echo "Failure. Changes detected:"; git diff; exit 1)
 
